// <auto-generated />
namespace PRS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class JudgeType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JudgeType));
        
        string IMigrationMetadata.Id
        {
            get { return "201407020732239_JudgeType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
