// <auto-generated />
namespace PRS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DecisionDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DecisionDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201403301318035_DecisionDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
