// <auto-generated />
namespace PRS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Migration02Feb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration02Feb));
        
        string IMigrationMetadata.Id
        {
            get { return "201402020631547_Migration02Feb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
